### ISSUE TITLE
No module named 'models.cifar10.resnet_OAT'

### ISSUE THREAD

**Issue by mqpziv** [VITA-Group/Once-for-All-Adversarial-Training#1]
from models.cifar10.resnet_OAT import ResNet34OAT
ModuleNotFoundError: No module named 'models.cifar10.resnet_OAT'

the current corresponding file is resnet_CAT?

**Comment by mqpziv** [comment]
Traceback (most recent call last):
  File "OAT.py", line 20, in <module>
    from attacks.pgd import PGD
ModuleNotFoundError: No module named 'attacks'

**Comment by htwang14** [comment]
Thanks for your interest in our work! The issues are fixed in the latest commit.
